# Generated by Django 3.2 on 2021-04-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_video', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
