# Generated by Django 3.2.4 on 2021-06-15 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('short_video', '0010_commentreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added', '-id']},
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['-date_added', '-id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date_added', '-id']},
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comment_reply_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
