# Generated by Django 3.2.4 on 2021-06-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_video', '0012_commentinform_commentreplyinform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
